### ISSUE TITLE
Limpeza de Dependências do ZF

### ISSUE THREAD

**Issue by wandersonwhcr** [wandersonwhcr/balance#173]
Ao invés de utilizarmos o `zendframework/zendframework` diretamente no `composer.json`, podemos utilizar cada componente que é realmente requerido para a execução deste projeto, como `zendframework/zend-db`. Isto melhorará a quantidade de bibliotecas instaladas em disco.

**Comment by wandersonwhcr** [comment]
Para verificar se todas as dependências foram definidas, executar o `phpunit`.

**Comment by wandersonwhcr** [comment]
@petersonwpm eu me coloquei como responsável.

Agora, tu deves criar um PR com o teu _branch_ `issue-173` no meu _branch_ `develop`. Lembre-se de que o teu _branch_ tem que estar alinhado com o meu _branch_ `master`: se não está, pf, faça um _rebase_.

**Comment by wandersonwhcr** [comment]
@petersonwpm pelo que vi, o teu _branch_ `issue-173` está devidamente alinhado com meu _branch_ `master` 👍

**Comment by wandersonwhcr** [comment]
Essa eu não conhecia!

```diff
diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..cf2636e
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1 @@
+/composer.lock -merge
```

Qual a moral?

**Comment by wandersonwhcr** [comment]
Rodei um `make tests` no teu _branch_ e notei que o pacote `fabpot/php-cs-fixer` foi atualizado da versão `v1.11` para versão `v1.13.3`, fazendo com que algumas verificações de _sniffer_ de código quebrassem.

Isso aconteceu porque o `composer.json` possui uma configuração para este pacote sem considerar a versão de _patch_. Eu fiz essa m# na revisão 41f8fb50. Podes configurar o `composer.json` com o valor correto para o pacote? Ficaremos assim:

```diff
diff --git a/composer.json b/composer.json
index 055e405..bc784d7 100644
--- a/composer.json
+++ b/composer.json
@@ -56,7 +56,7 @@
         "sebastian/phpcpd": "2.0.*",
         "jakub-onderka/php-parallel-lint": "0.9.*",
         "squizlabs/php_codesniffer": "2.5.*",
-        "fabpot/php-cs-fixer": "1.*",
+        "fabpot/php-cs-fixer": "1.11.*",
         "phpmd/phpmd": "2.3.*",
         "neilime/zf2-twb-bundle": "2.6.*"
     },
```

**Comment by petersonwpm** [comment]
/composer.lock - merge

Sempre que vamos realizar alguma operação no git que resulte em merge, acabamos tendo confltos no composer.lock, isso aconte devido as atualizações controladas pelo composer.
Esta instrução serve para informar ao git que não queremos realizar merge deste arquivo e básicamente ficaremos com versão mais recente.

No fim de um rebase é importante executar composer update --lock

referência: https://goo.gl/43zo2V

**Comment by petersonwpm** [comment]
O pacote fabpot/php-cs-fixer foi substituido por friendsofphp/php-cs-fixer, não seria interessante atualizar para esse então?

**Comment by wandersonwhcr** [comment]
Podemos criar uma outra _issue_ para esta atualização. Acho que a moral, agora, é quebrar o Zend Framework e manter as coisas rodando.

**Comment by petersonwpm** [comment]
blz, concordo, farei o ajuste e depois o PR

**Comment by wandersonwhcr** [comment]
Aguardando o PR.

**Comment by wandersonwhcr** [comment]
O Travis não estava configurado para fazer _builds_ para PRs.

As próximas serão executadas corretamente.
