### ISSUE TITLE
Estrutura de Banco de Dados

### ISSUE THREAD

**Issue by wandersonwhcr** [wandersonwhcr/balance#6]
Precisamos criar a estrutura básica de banco de dados para armazenar as informações do Balance. Basicamente, o Balance necessita destas informações:

```
contas
    - id
    - nome
    - tipo (ativo|passivo)
    - descrição
lançamentos
    - id
    - data e hora
    - descrição
entradas
    - contas -> id
    - lançamentos -> id
    - tipo (crédito|débito)
    - valor
```

Utilizar o PHINX para criação das _migrations_ de banco de dados. Colocar as _migrations_ dentro do módulo e não na raiz do projeto. Para cada tabela gerada, criar uma _migration_ separada.

**Comment by wandersonwhcr** [comment]
Só para constar, no sistema antigo eu chamei contas de _bills_, lançamentos de _postings_ e entradas de _entries_.

**Comment by petersonwpm** [comment]
Feito!

**Comment by wandersonwhcr** [comment]
Reabrindo para _merge_.

**Comment by wandersonwhcr** [comment]
Efetuado o _merge_.
